version: '2'

services:
   travian:
      build: travian
      container_name: travian
      ports:
         - "3000:80"
      volumes:
         - ./appdata/TravianZ:/var/www/html

   mysql:
      image: "mysql:8.0"
      container_name: travian-sql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=travian
         - MYSQL_USER=travian
         - MYSQL_PASSWORD=travian
      volumes:
         - ./appdata/mysql/data:/var/lib/mysql
